### PR TITLE
Sentinel workaround, should fix #8

### LINKED ISSUE #8: Assert failure tessellating planar triangle
Passing the following triangle to the tessellator causes an assert failure:
```
Assertion failed: (VertLeq( u, v ) && VertLeq( v, w )), function tesedgeSign, file ../Source/geom.c, line 83.
```

```
-70.4956,14.872283,14.6119
-70.4956,14.8722944,32.6832
-70.4956,14.872283,14.6119
```

The cause seems to be that the sentinels used for the edge dict touches the bounding box when any dimension of the bounding box is 0. The is again amplified by the worst-case normal being chosen for collinear input polygons. I'll send a patch for the latter issue shortly.

A special case of this issue is when a polygon is collinear in an axis-aligned fashion. In this case, my fix for the normal vector won't help:
```
0,0,0
0,0,1
0,0,2
```

### PR DESCRIPTION
**Pull request by kintel**
Not sure if this is the best solution but it does appear to fix #8.

### CODE REVIEW

File: Source/sweep.c [hunk 1]
```diff
@@ -1121,10 +1121,10 @@ static void InitEdgeDict( TESStesselator *tess )
 	w = (tess->bmax[0] - tess->bmin[0]);
 	h = (tess->bmax[1] - tess->bmin[1]);
 
-	smin = tess->bmin[0] - w;
-	smax = tess->bmax[0] + w;
-	tmin = tess->bmin[1] - h;
-	tmax = tess->bmax[1] + h;
+	smin = tess->bmin[0] - w - 0.01;
```
Comment (memononen) [inline Source/sweep.c]: Looks good, would you mind updating this with a comment? I.e: "Make sure sentinels are not coincident."

**Comment by kintel** [comment]
Should be clarified now

**Comment by memononen** [comment]
Thanks!
